### ISSUE TITLE
[BUG] Dendro crashes during a sign in operation if the username field is filled up but the password field is left empty

### ISSUE THREAD

**Issue by NelsonPereira1991** [feup-infolab/dendro#284]
### Dendro Version if known (or site URL)
https://github.com/feup-infolab/dendro/tree/machine-plus-human-identifiers

### Please describe the expected behaviour
Should give an error saying that the password field is required

### Please describe the actual behaviour
Dendro is crashing

Error:

Error: Failed to serialize user into session
    at pass (/Users/nelsonpereira/Desktop/Infolab/dendroRepository/dendro/node_modules/passport/lib/authenticator.js:281:19)
    at serialized (/Users/nelsonpereira/Desktop/Infolab/dendroRepository/dendro/node_modules/passport/lib/authenticator.js:286:7)
    at /Users/nelsonpereira/Desktop/Infolab/dendroRepository/dendro/src/bootup/init/setup_passport.js:57:9
    at pass (/Users/nelsonpereira/Desktop/Infolab/dendroRepository/dendro/node_modules/passport/lib/authenticator.js:294:9)
    at Authenticator.serializeUser (/Users/nelsonpereira/Desktop/Infolab/dendroRepository/dendro/node_modules/passport/lib/authenticator.js:299:5)
    at SessionManager.logIn (/Users/nelsonpereira/Desktop/Infolab/dendroRepository/dendro/node_modules/passport/lib/sessionmanager.js:14:8)
    at IncomingMessage.req.login.req.logIn (/Users/nelsonpereira/Desktop/Infolab/dendroRepository/dendro/node_modules/passport/lib/http/request.js:50:33)
    at /Users/nelsonpereira/Desktop/Infolab/dendroRepository/dendro/src/controllers/auth.js:37:29
    at allFailed (/Users/nelsonpereira/Desktop/Infolab/dendroRepository/dendro/node_modules/passport/lib/middleware/authenticate.js:107:18)
    at attempt (/Users/nelsonpereira/Desktop/Infolab/dendroRepository/dendro/node_modules/passport/lib/middleware/authenticate.js:180:28)

### What steps can be taken to reproduce the issue? 
Try to login but only fill in the username field, leave the password one blank

**Comment by NelsonPereira1991** [comment]
FIXED IN https://github.com/feup-infolab/dendro/pull/285
